### ISSUE TITLE
[Todo] 유진(~8/15)

### ISSUE THREAD

**Issue by Ujaa** [Godeok/ChanNuLi#59]
**마이페이지 관련 구현 사항**
- [x] 게임 최고 기록 연결
- [x] 마이페이지 회원정보 수정 페이지 구현
- [x] 회원정보+질병 수정 페이지 레이아웃 정리
---
- [ ] 게임 초기화 기능
- [ ] 자가진단 통계 레이아웃 제작
- [ ] 리소스 구상

**Comment by Ujaa** [comment]
여기서부터는 일요일에 진행
**파일 정리**
- [ ]  1. 애니메이션 이름 통일(anim_쓰이는 곳_애니메이션 설명)
- [ ]  2. 안 쓰는 파일 삭제(recyclerview, image...)
- [ ]  3. drawable 이름 통일
- [ ]  4. style 안 쓰는 거 삭제, 쓰는 거 정리

**변수명 정리**
- [ ] java
- [ ] xml

*res/color 로 변경해야 하는 것 변경해서 정리*
