### ISSUE TITLE
[Todo] 유진 (~8/31)

### ISSUE THREAD

**Issue by Ujaa** [Godeok/ChanNuLi#74]
- [x] 마이페이지 건강상태 없을 때 레이아웃
- [x] 자가진단 없을 때 레이아웃 
- [x] 자가진단 레이아웃 변경
- [x] 자가진단 결과 화면 레이아웃 변경
- [x] #79
- [x] 출처 없애기
- [x] 건강 정보 검색 레이아웃 변경
- [x] 게임 메인 화면 레이아웃 
- [ ] 게임1 사람 얼굴
- [ ] 칠판 배경
- [ ] 탁자
